DECLARE
  NDAYS NUMBER;
BEGIN
  NDAYS := 1000;
  
  SCORING_PKG.CALCULATE_SELLER_SCORING(
    NDAYS => NDAYS
  );
--rollback; 
END;
/
CREATE INDEX REVIEW_USER_MODIFIED_IDX
ON REVIEW ("USER_ID","ROLE", "STATUS", "MODIFIED")
tablespace team2_indexes;
/

drop index REVIEW_USER_MODIFIED_IDX;
/
CREATE INDEX REVIEW_USER_CREATED_IDX
ON REVIEW ("USER_ID","CREATED")
tablespace team2_indexes;
/
drop index REVIEW_USER_CREATED_IDX;
/



DROP TABLE SCORE;
/

CREATE TABLE "BDII_TEAM3"."SCORE" 
(	"USER_ID" NUMBER(10,0), 
	"LAST_WEEK_POSITIVE" NUMBER(10,0), 
	"LAST_WEEK_NEUTRAL" NUMBER(10,0), 
	"LAST_WEEK_NEGATIVE" NUMBER(10,0), 
	"LAST_MONTH_POSITIVE" NUMBER(10,0), 
	"LAST_MONTH_NEUTRAL" NUMBER(10,0), 
	"LAST_MONTH_NEGATIVE" NUMBER(10,0), 
	"LAST_6MONTH_POSITIVE" NUMBER(10,0), 
	"LAST_6MONTH_NEUTRAL" NUMBER(10,0), 
	"LAST_6MONTH_NEGATIVE" NUMBER(10,0), 
	"SCORE" NUMBER(10,2), 
	"STATUS" CHAR(10 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"MODIFIED" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 10 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 121
PCTINCREASE 5 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "BDII_TEAM3_DATA" ;
/



SELECT DISTINCT USER_ID 
   FROM REVIEW 
   WHERE ROLE = 'SELLER' 
   AND STATUS = 'PUBLISHED' 
   AND MODIFIED >= ( SYSDATE - 1000 ) 
   UNION
   SELECT USER_ID
   FROM SCORE
   WHERE MODIFIED < ( SYSDATE - 7 )
/   

SELECT CREATED, SCORE
          FROM REVIEW
          WHERE USER_ID = 123
          AND CREATED > SYSDATE - 180
/

AlTER TABLE SCORE ADD CONSTRAINT "SCORE_EUSER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "BDII_TEAM2"."EUSER" ("ID") ENABLE;
/

AlTER TABLE EUSER 
MODIFY CREATED date;
/
AlTER TABLE EUSER 
MODIFY MODIFIED date;
/


AlTER TABLE SCORE 
MODIFY CREATED date;
/
AlTER TABLE SCORE 
MODIFY MODIFIED date;
/
AlTER TABLE Score 
MODIFY Status char(10);
/
AlTER TABLE Score 
MODIFY Status number(3, 2);
/

AlTER TABLE REVIEW 
MODIFY COMMENTS varchar2(200);
/

AlTER TABLE Sale 
MODIFY CREATED date;
/

AlTER TABLE Sale 
MODIFY MODIFIED date;
/

AlTER TABLE Review 
MODIFY CREATED date;
/

AlTER TABLE Review 
MODIFY MODIFIED date;
/

ALTER TABLE EUSER PCTFREE 0;
ALTER TABLE REVIEW PCTFREE 0;
ALTER TABLE SALE PCTFREE 0;
/

drop index REVIEW_STATUS_IDX;
/

analyze table EMPLE compute statistics;
select TABLE_NAME, NUM_ROWS, BLOCKS, EMPTY_BLOCKS, AVG_ROW_LEN
from USER_TABLES
where TABLE_NAME='EMPLE'
/


                
